// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ConsoleLogProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ConsoleLogProto GetRootAsConsoleLogProto(ByteBuffer _bb) { return GetRootAsConsoleLogProto(_bb, new ConsoleLogProto()); }
  public static ConsoleLogProto GetRootAsConsoleLogProto(ByteBuffer _bb, ConsoleLogProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ConsoleLogProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ConsoleLogMessageProto? Messages(int j) { int o = __p.__offset(4); return o != 0 ? (ConsoleLogMessageProto?)(new ConsoleLogMessageProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MessagesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ConsoleLogProto> CreateConsoleLogProto(FlatBufferBuilder builder,
      VectorOffset messagesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ConsoleLogProto.AddMessages(builder, messagesOffset);
    return ConsoleLogProto.EndConsoleLogProto(builder);
  }

  public static void StartConsoleLogProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMessages(FlatBufferBuilder builder, VectorOffset messagesOffset) { builder.AddOffset(0, messagesOffset.Value, 0); }
  public static VectorOffset CreateMessagesVector(FlatBufferBuilder builder, Offset<ConsoleLogMessageProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMessagesVectorBlock(FlatBufferBuilder builder, Offset<ConsoleLogMessageProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartMessagesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ConsoleLogProto> EndConsoleLogProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ConsoleLogProto>(o);
  }
};

