// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ConstructorProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ConstructorProto GetRootAsConstructorProto(ByteBuffer _bb) { return GetRootAsConstructorProto(_bb, new ConstructorProto()); }
  public static ConstructorProto GetRootAsConstructorProto(ByteBuffer _bb, ConstructorProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ConstructorProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MethodArgumentProto? Arguments(int j) { int o = __p.__offset(4); return o != 0 ? (MethodArgumentProto?)(new MethodArgumentProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ArgumentsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ConstructorProto> CreateConstructorProto(FlatBufferBuilder builder,
      VectorOffset argumentsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ConstructorProto.AddArguments(builder, argumentsOffset);
    return ConstructorProto.EndConstructorProto(builder);
  }

  public static void StartConstructorProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddArguments(FlatBufferBuilder builder, VectorOffset argumentsOffset) { builder.AddOffset(0, argumentsOffset.Value, 0); }
  public static VectorOffset CreateArgumentsVector(FlatBufferBuilder builder, Offset<MethodArgumentProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateArgumentsVectorBlock(FlatBufferBuilder builder, Offset<MethodArgumentProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartArgumentsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ConstructorProto> EndConstructorProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ConstructorProto>(o);
  }
};

