// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DataUpdateMessageProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static DataUpdateMessageProto GetRootAsDataUpdateMessageProto(ByteBuffer _bb) { return GetRootAsDataUpdateMessageProto(_bb, new DataUpdateMessageProto()); }
  public static DataUpdateMessageProto GetRootAsDataUpdateMessageProto(ByteBuffer _bb, DataUpdateMessageProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DataUpdateMessageProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public DataDeltaBytesProto? Deltas(int j) { int o = __p.__offset(4); return o != 0 ? (DataDeltaBytesProto?)(new DataDeltaBytesProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DeltasLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<DataUpdateMessageProto> CreateDataUpdateMessageProto(FlatBufferBuilder builder,
      VectorOffset deltasOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DataUpdateMessageProto.AddDeltas(builder, deltasOffset);
    return DataUpdateMessageProto.EndDataUpdateMessageProto(builder);
  }

  public static void StartDataUpdateMessageProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDeltas(FlatBufferBuilder builder, VectorOffset deltasOffset) { builder.AddOffset(0, deltasOffset.Value, 0); }
  public static VectorOffset CreateDeltasVector(FlatBufferBuilder builder, Offset<DataDeltaBytesProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDeltasVectorBlock(FlatBufferBuilder builder, Offset<DataDeltaBytesProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDeltasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<DataUpdateMessageProto> EndDataUpdateMessageProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // deltas
    return new Offset<DataUpdateMessageProto>(o);
  }
};

