// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DeleteWorkerResponseProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static DeleteWorkerResponseProto GetRootAsDeleteWorkerResponseProto(ByteBuffer _bb) { return GetRootAsDeleteWorkerResponseProto(_bb, new DeleteWorkerResponseProto()); }
  public static DeleteWorkerResponseProto GetRootAsDeleteWorkerResponseProto(ByteBuffer _bb, DeleteWorkerResponseProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DeleteWorkerResponseProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ErrorCodeResponseProto? Error { get { int o = __p.__offset(4); return o != 0 ? (ErrorCodeResponseProto?)(new ErrorCodeResponseProto()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<DeleteWorkerResponseProto> CreateDeleteWorkerResponseProto(FlatBufferBuilder builder,
      Offset<ErrorCodeResponseProto> errorOffset = default(Offset<ErrorCodeResponseProto>)) {
    builder.StartTable(1);
    DeleteWorkerResponseProto.AddError(builder, errorOffset);
    return DeleteWorkerResponseProto.EndDeleteWorkerResponseProto(builder);
  }

  public static void StartDeleteWorkerResponseProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddError(FlatBufferBuilder builder, Offset<ErrorCodeResponseProto> errorOffset) { builder.AddOffset(0, errorOffset.Value, 0); }
  public static Offset<DeleteWorkerResponseProto> EndDeleteWorkerResponseProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<DeleteWorkerResponseProto>(o);
  }
};

