// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ErrorCodeResponseProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ErrorCodeResponseProto GetRootAsErrorCodeResponseProto(ByteBuffer _bb) { return GetRootAsErrorCodeResponseProto(_bb, new ErrorCodeResponseProto()); }
  public static ErrorCodeResponseProto GetRootAsErrorCodeResponseProto(ByteBuffer _bb, ErrorCodeResponseProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ErrorCodeResponseProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort ErrorCode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<ErrorCodeResponseProto> CreateErrorCodeResponseProto(FlatBufferBuilder builder,
      ushort error_code = 0) {
    builder.StartTable(1);
    ErrorCodeResponseProto.AddErrorCode(builder, error_code);
    return ErrorCodeResponseProto.EndErrorCodeResponseProto(builder);
  }

  public static void StartErrorCodeResponseProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, ushort errorCode) { builder.AddUshort(0, errorCode, 0); }
  public static Offset<ErrorCodeResponseProto> EndErrorCodeResponseProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ErrorCodeResponseProto>(o);
  }
};

