// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ExceptionResponseProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ExceptionResponseProto GetRootAsExceptionResponseProto(ByteBuffer _bb) { return GetRootAsExceptionResponseProto(_bb, new ExceptionResponseProto()); }
  public static ExceptionResponseProto GetRootAsExceptionResponseProto(ByteBuffer _bb, ExceptionResponseProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ExceptionResponseProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Stack { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStackBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetStackBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetStackArray() { return __p.__vector_as_array<byte>(4); }
  public string Message { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<ExceptionResponseProto> CreateExceptionResponseProto(FlatBufferBuilder builder,
      StringOffset stackOffset = default(StringOffset),
      StringOffset messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    ExceptionResponseProto.AddMessage(builder, messageOffset);
    ExceptionResponseProto.AddStack(builder, stackOffset);
    return ExceptionResponseProto.EndExceptionResponseProto(builder);
  }

  public static void StartExceptionResponseProto(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddStack(FlatBufferBuilder builder, StringOffset stackOffset) { builder.AddOffset(0, stackOffset.Value, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(1, messageOffset.Value, 0); }
  public static Offset<ExceptionResponseProto> EndExceptionResponseProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ExceptionResponseProto>(o);
  }
};

