// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FreeFunctionProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static FreeFunctionProto GetRootAsFreeFunctionProto(ByteBuffer _bb) { return GetRootAsFreeFunctionProto(_bb, new FreeFunctionProto()); }
  public static FreeFunctionProto GetRootAsFreeFunctionProto(ByteBuffer _bb, FreeFunctionProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FreeFunctionProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string SourceCode { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSourceCodeBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSourceCodeBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSourceCodeArray() { return __p.__vector_as_array<byte>(4); }
  public string FunctionName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFunctionNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetFunctionNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetFunctionNameArray() { return __p.__vector_as_array<byte>(6); }
  public MethodArgumentProto? Arguments(int j) { int o = __p.__offset(8); return o != 0 ? (MethodArgumentProto?)(new MethodArgumentProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ArgumentsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string ReturnType { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReturnTypeBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetReturnTypeBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetReturnTypeArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<FreeFunctionProto> CreateFreeFunctionProto(FlatBufferBuilder builder,
      StringOffset source_codeOffset = default(StringOffset),
      StringOffset function_nameOffset = default(StringOffset),
      VectorOffset argumentsOffset = default(VectorOffset),
      StringOffset return_typeOffset = default(StringOffset)) {
    builder.StartTable(4);
    FreeFunctionProto.AddReturnType(builder, return_typeOffset);
    FreeFunctionProto.AddArguments(builder, argumentsOffset);
    FreeFunctionProto.AddFunctionName(builder, function_nameOffset);
    FreeFunctionProto.AddSourceCode(builder, source_codeOffset);
    return FreeFunctionProto.EndFreeFunctionProto(builder);
  }

  public static void StartFreeFunctionProto(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddSourceCode(FlatBufferBuilder builder, StringOffset sourceCodeOffset) { builder.AddOffset(0, sourceCodeOffset.Value, 0); }
  public static void AddFunctionName(FlatBufferBuilder builder, StringOffset functionNameOffset) { builder.AddOffset(1, functionNameOffset.Value, 0); }
  public static void AddArguments(FlatBufferBuilder builder, VectorOffset argumentsOffset) { builder.AddOffset(2, argumentsOffset.Value, 0); }
  public static VectorOffset CreateArgumentsVector(FlatBufferBuilder builder, Offset<MethodArgumentProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateArgumentsVectorBlock(FlatBufferBuilder builder, Offset<MethodArgumentProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartArgumentsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddReturnType(FlatBufferBuilder builder, StringOffset returnTypeOffset) { builder.AddOffset(3, returnTypeOffset.Value, 0); }
  public static Offset<FreeFunctionProto> EndFreeFunctionProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // source_code
    return new Offset<FreeFunctionProto>(o);
  }
};

