// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FreeClassProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static FreeClassProto GetRootAsFreeClassProto(ByteBuffer _bb) { return GetRootAsFreeClassProto(_bb, new FreeClassProto()); }
  public static FreeClassProto GetRootAsFreeClassProto(ByteBuffer _bb, FreeClassProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FreeClassProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ConstructorProto? Ctor { get { int o = __p.__offset(4); return o != 0 ? (ConstructorProto?)(new ConstructorProto()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string SourceCode { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSourceCodeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetSourceCodeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetSourceCodeArray() { return __p.__vector_as_array<byte>(6); }
  public string ClassName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetClassNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetClassNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetClassNameArray() { return __p.__vector_as_array<byte>(8); }
  public MethodProto? Methods(int j) { int o = __p.__offset(10); return o != 0 ? (MethodProto?)(new MethodProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MethodsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FreeClassProto> CreateFreeClassProto(FlatBufferBuilder builder,
      Offset<ConstructorProto> ctorOffset = default(Offset<ConstructorProto>),
      StringOffset source_codeOffset = default(StringOffset),
      StringOffset class_nameOffset = default(StringOffset),
      VectorOffset methodsOffset = default(VectorOffset)) {
    builder.StartTable(4);
    FreeClassProto.AddMethods(builder, methodsOffset);
    FreeClassProto.AddClassName(builder, class_nameOffset);
    FreeClassProto.AddSourceCode(builder, source_codeOffset);
    FreeClassProto.AddCtor(builder, ctorOffset);
    return FreeClassProto.EndFreeClassProto(builder);
  }

  public static void StartFreeClassProto(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddCtor(FlatBufferBuilder builder, Offset<ConstructorProto> ctorOffset) { builder.AddOffset(0, ctorOffset.Value, 0); }
  public static void AddSourceCode(FlatBufferBuilder builder, StringOffset sourceCodeOffset) { builder.AddOffset(1, sourceCodeOffset.Value, 0); }
  public static void AddClassName(FlatBufferBuilder builder, StringOffset classNameOffset) { builder.AddOffset(2, classNameOffset.Value, 0); }
  public static void AddMethods(FlatBufferBuilder builder, VectorOffset methodsOffset) { builder.AddOffset(3, methodsOffset.Value, 0); }
  public static VectorOffset CreateMethodsVector(FlatBufferBuilder builder, Offset<MethodProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMethodsVectorBlock(FlatBufferBuilder builder, Offset<MethodProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartMethodsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FreeClassProto> EndFreeClassProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // ctor
    builder.Required(o, 6);  // source_code
    return new Offset<FreeClassProto>(o);
  }
};

