// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct GetDataResponseProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static GetDataResponseProto GetRootAsGetDataResponseProto(ByteBuffer _bb) { return GetRootAsGetDataResponseProto(_bb, new GetDataResponseProto()); }
  public static GetDataResponseProto GetRootAsGetDataResponseProto(ByteBuffer _bb, GetDataResponseProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetDataResponseProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public NestedDataProto? Data(int j) { int o = __p.__offset(4); return o != 0 ? (NestedDataProto?)(new NestedDataProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GetDataResponseProto> CreateGetDataResponseProto(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(1);
    GetDataResponseProto.AddData(builder, dataOffset);
    return GetDataResponseProto.EndGetDataResponseProto(builder);
  }

  public static void StartGetDataResponseProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, Offset<NestedDataProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, Offset<NestedDataProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GetDataResponseProto> EndGetDataResponseProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GetDataResponseProto>(o);
  }
};

