// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct InboundDataDeltaProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static InboundDataDeltaProto GetRootAsInboundDataDeltaProto(ByteBuffer _bb) { return GetRootAsInboundDataDeltaProto(_bb, new InboundDataDeltaProto()); }
  public static InboundDataDeltaProto GetRootAsInboundDataDeltaProto(ByteBuffer _bb, InboundDataDeltaProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InboundDataDeltaProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort ClassId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ulong ObjectVersion { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string PrimaryKey { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPrimaryKeyBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetPrimaryKeyBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetPrimaryKeyArray() { return __p.__vector_as_array<byte>(8); }
  public NestedPropertyProto? Properties(int j) { int o = __p.__offset(10); return o != 0 ? (NestedPropertyProto?)(new NestedPropertyProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PropertiesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string DeletedProperties(int j) { int o = __p.__offset(12); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int DeletedPropertiesLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<InboundDataDeltaProto> CreateInboundDataDeltaProto(FlatBufferBuilder builder,
      ushort class_id = 0,
      ulong object_version = 0,
      StringOffset primary_keyOffset = default(StringOffset),
      VectorOffset propertiesOffset = default(VectorOffset),
      VectorOffset deleted_propertiesOffset = default(VectorOffset)) {
    builder.StartTable(5);
    InboundDataDeltaProto.AddObjectVersion(builder, object_version);
    InboundDataDeltaProto.AddDeletedProperties(builder, deleted_propertiesOffset);
    InboundDataDeltaProto.AddProperties(builder, propertiesOffset);
    InboundDataDeltaProto.AddPrimaryKey(builder, primary_keyOffset);
    InboundDataDeltaProto.AddClassId(builder, class_id);
    return InboundDataDeltaProto.EndInboundDataDeltaProto(builder);
  }

  public static void StartInboundDataDeltaProto(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddClassId(FlatBufferBuilder builder, ushort classId) { builder.AddUshort(0, classId, 0); }
  public static void AddObjectVersion(FlatBufferBuilder builder, ulong objectVersion) { builder.AddUlong(1, objectVersion, 0); }
  public static void AddPrimaryKey(FlatBufferBuilder builder, StringOffset primaryKeyOffset) { builder.AddOffset(2, primaryKeyOffset.Value, 0); }
  public static void AddProperties(FlatBufferBuilder builder, VectorOffset propertiesOffset) { builder.AddOffset(3, propertiesOffset.Value, 0); }
  public static VectorOffset CreatePropertiesVector(FlatBufferBuilder builder, Offset<NestedPropertyProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePropertiesVectorBlock(FlatBufferBuilder builder, Offset<NestedPropertyProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartPropertiesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDeletedProperties(FlatBufferBuilder builder, VectorOffset deletedPropertiesOffset) { builder.AddOffset(4, deletedPropertiesOffset.Value, 0); }
  public static VectorOffset CreateDeletedPropertiesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDeletedPropertiesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDeletedPropertiesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<InboundDataDeltaProto> EndInboundDataDeltaProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 8);  // primary_key
    return new Offset<InboundDataDeltaProto>(o);
  }
};

