// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MapValueItemProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static MapValueItemProto GetRootAsMapValueItemProto(ByteBuffer _bb) { return GetRootAsMapValueItemProto(_bb, new MapValueItemProto()); }
  public static MapValueItemProto GetRootAsMapValueItemProto(ByteBuffer _bb, MapValueItemProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MapValueItemProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ValueProto? Key { get { int o = __p.__offset(4); return o != 0 ? (ValueProto?)(new ValueProto()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public ValueProto? Value { get { int o = __p.__offset(6); return o != 0 ? (ValueProto?)(new ValueProto()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<MapValueItemProto> CreateMapValueItemProto(FlatBufferBuilder builder,
      Offset<ValueProto> keyOffset = default(Offset<ValueProto>),
      Offset<ValueProto> valueOffset = default(Offset<ValueProto>)) {
    builder.StartTable(2);
    MapValueItemProto.AddValue(builder, valueOffset);
    MapValueItemProto.AddKey(builder, keyOffset);
    return MapValueItemProto.EndMapValueItemProto(builder);
  }

  public static void StartMapValueItemProto(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddKey(FlatBufferBuilder builder, Offset<ValueProto> keyOffset) { builder.AddOffset(0, keyOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, Offset<ValueProto> valueOffset) { builder.AddOffset(1, valueOffset.Value, 0); }
  public static Offset<MapValueItemProto> EndMapValueItemProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MapValueItemProto>(o);
  }
};

