// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MessageClassProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static MessageClassProto GetRootAsMessageClassProto(ByteBuffer _bb) { return GetRootAsMessageClassProto(_bb, new MessageClassProto()); }
  public static MessageClassProto GetRootAsMessageClassProto(ByteBuffer _bb, MessageClassProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MessageClassProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort ClassId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public string ClassName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetClassNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetClassNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetClassNameArray() { return __p.__vector_as_array<byte>(6); }
  public string SourceCode { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSourceCodeBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetSourceCodeBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetSourceCodeArray() { return __p.__vector_as_array<byte>(8); }
  public ushort FileNameId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ConstructorProto? Ctor { get { int o = __p.__offset(12); return o != 0 ? (ConstructorProto?)(new ConstructorProto()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public MethodProto? Methods(int j) { int o = __p.__offset(14); return o != 0 ? (MethodProto?)(new MethodProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MethodsLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MessageClassProto> CreateMessageClassProto(FlatBufferBuilder builder,
      ushort class_id = 0,
      StringOffset class_nameOffset = default(StringOffset),
      StringOffset source_codeOffset = default(StringOffset),
      ushort file_name_id = 0,
      Offset<ConstructorProto> ctorOffset = default(Offset<ConstructorProto>),
      VectorOffset methodsOffset = default(VectorOffset)) {
    builder.StartTable(6);
    MessageClassProto.AddMethods(builder, methodsOffset);
    MessageClassProto.AddCtor(builder, ctorOffset);
    MessageClassProto.AddSourceCode(builder, source_codeOffset);
    MessageClassProto.AddClassName(builder, class_nameOffset);
    MessageClassProto.AddFileNameId(builder, file_name_id);
    MessageClassProto.AddClassId(builder, class_id);
    return MessageClassProto.EndMessageClassProto(builder);
  }

  public static void StartMessageClassProto(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddClassId(FlatBufferBuilder builder, ushort classId) { builder.AddUshort(0, classId, 0); }
  public static void AddClassName(FlatBufferBuilder builder, StringOffset classNameOffset) { builder.AddOffset(1, classNameOffset.Value, 0); }
  public static void AddSourceCode(FlatBufferBuilder builder, StringOffset sourceCodeOffset) { builder.AddOffset(2, sourceCodeOffset.Value, 0); }
  public static void AddFileNameId(FlatBufferBuilder builder, ushort fileNameId) { builder.AddUshort(3, fileNameId, 0); }
  public static void AddCtor(FlatBufferBuilder builder, Offset<ConstructorProto> ctorOffset) { builder.AddOffset(4, ctorOffset.Value, 0); }
  public static void AddMethods(FlatBufferBuilder builder, VectorOffset methodsOffset) { builder.AddOffset(5, methodsOffset.Value, 0); }
  public static VectorOffset CreateMethodsVector(FlatBufferBuilder builder, Offset<MethodProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMethodsVectorBlock(FlatBufferBuilder builder, Offset<MethodProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartMethodsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MessageClassProto> EndMessageClassProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 6);  // class_name
    builder.Required(o, 8);  // source_code
    builder.Required(o, 12);  // ctor
    return new Offset<MessageClassProto>(o);
  }
};

