// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MessageMessageProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static MessageMessageProto GetRootAsMessageMessageProto(ByteBuffer _bb) { return GetRootAsMessageMessageProto(_bb, new MessageMessageProto()); }
  public static MessageMessageProto GetRootAsMessageMessageProto(ByteBuffer _bb, MessageMessageProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MessageMessageProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MessageBytesProto? Event { get { int o = __p.__offset(4); return o != 0 ? (MessageBytesProto?)(new MessageBytesProto()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public DataDeltaBytesProto? Deltas(int j) { int o = __p.__offset(6); return o != 0 ? (DataDeltaBytesProto?)(new DataDeltaBytesProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DeltasLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MessageMessageProto> CreateMessageMessageProto(FlatBufferBuilder builder,
      Offset<MessageBytesProto> eventOffset = default(Offset<MessageBytesProto>),
      VectorOffset deltasOffset = default(VectorOffset)) {
    builder.StartTable(2);
    MessageMessageProto.AddDeltas(builder, deltasOffset);
    MessageMessageProto.AddEvent(builder, eventOffset);
    return MessageMessageProto.EndMessageMessageProto(builder);
  }

  public static void StartMessageMessageProto(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddEvent(FlatBufferBuilder builder, Offset<MessageBytesProto> eventOffset) { builder.AddOffset(0, eventOffset.Value, 0); }
  public static void AddDeltas(FlatBufferBuilder builder, VectorOffset deltasOffset) { builder.AddOffset(1, deltasOffset.Value, 0); }
  public static VectorOffset CreateDeltasVector(FlatBufferBuilder builder, Offset<DataDeltaBytesProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDeltasVectorBlock(FlatBufferBuilder builder, Offset<DataDeltaBytesProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDeltasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<MessageMessageProto> EndMessageMessageProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // event
    return new Offset<MessageMessageProto>(o);
  }
};

