// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ObjectValueProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ObjectValueProto GetRootAsObjectValueProto(ByteBuffer _bb) { return GetRootAsObjectValueProto(_bb, new ObjectValueProto()); }
  public static ObjectValueProto GetRootAsObjectValueProto(ByteBuffer _bb, ObjectValueProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ObjectValueProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PropertyProto? Properties(int j) { int o = __p.__offset(4); return o != 0 ? (PropertyProto?)(new PropertyProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PropertiesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ObjectValueProto> CreateObjectValueProto(FlatBufferBuilder builder,
      VectorOffset propertiesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ObjectValueProto.AddProperties(builder, propertiesOffset);
    return ObjectValueProto.EndObjectValueProto(builder);
  }

  public static void StartObjectValueProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddProperties(FlatBufferBuilder builder, VectorOffset propertiesOffset) { builder.AddOffset(0, propertiesOffset.Value, 0); }
  public static VectorOffset CreatePropertiesVector(FlatBufferBuilder builder, Offset<PropertyProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePropertiesVectorBlock(FlatBufferBuilder builder, Offset<PropertyProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartPropertiesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ObjectValueProto> EndObjectValueProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ObjectValueProto>(o);
  }
};

