// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ObjectPropertiesIndexProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ObjectPropertiesIndexProto GetRootAsObjectPropertiesIndexProto(ByteBuffer _bb) { return GetRootAsObjectPropertiesIndexProto(_bb, new ObjectPropertiesIndexProto()); }
  public static ObjectPropertiesIndexProto GetRootAsObjectPropertiesIndexProto(ByteBuffer _bb, ObjectPropertiesIndexProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ObjectPropertiesIndexProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Properties(int j) { int o = __p.__offset(4); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int PropertiesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ObjectPropertiesIndexProto> CreateObjectPropertiesIndexProto(FlatBufferBuilder builder,
      VectorOffset propertiesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ObjectPropertiesIndexProto.AddProperties(builder, propertiesOffset);
    return ObjectPropertiesIndexProto.EndObjectPropertiesIndexProto(builder);
  }

  public static void StartObjectPropertiesIndexProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddProperties(FlatBufferBuilder builder, VectorOffset propertiesOffset) { builder.AddOffset(0, propertiesOffset.Value, 0); }
  public static VectorOffset CreatePropertiesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePropertiesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartPropertiesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ObjectPropertiesIndexProto> EndObjectPropertiesIndexProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ObjectPropertiesIndexProto>(o);
  }
};

