// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ObjectInstanceProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ObjectInstanceProto GetRootAsObjectInstanceProto(ByteBuffer _bb) { return GetRootAsObjectInstanceProto(_bb, new ObjectInstanceProto()); }
  public static ObjectInstanceProto GetRootAsObjectInstanceProto(ByteBuffer _bb, ObjectInstanceProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ObjectInstanceProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Version { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public bool Deleted { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public byte Type { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<ObjectInstanceProto> CreateObjectInstanceProto(FlatBufferBuilder builder,
      ulong version = 0,
      bool deleted = false,
      byte type = 0) {
    builder.StartTable(3);
    ObjectInstanceProto.AddVersion(builder, version);
    ObjectInstanceProto.AddType(builder, type);
    ObjectInstanceProto.AddDeleted(builder, deleted);
    return ObjectInstanceProto.EndObjectInstanceProto(builder);
  }

  public static void StartObjectInstanceProto(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddVersion(FlatBufferBuilder builder, ulong version) { builder.AddUlong(0, version, 0); }
  public static void AddDeleted(FlatBufferBuilder builder, bool deleted) { builder.AddBool(1, deleted, false); }
  public static void AddType(FlatBufferBuilder builder, byte type) { builder.AddByte(2, type, 0); }
  public static Offset<ObjectInstanceProto> EndObjectInstanceProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ObjectInstanceProto>(o);
  }
};

