// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct RiverUserResponseProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static RiverUserResponseProto GetRootAsRiverUserResponseProto(ByteBuffer _bb) { return GetRootAsRiverUserResponseProto(_bb, new RiverUserResponseProto()); }
  public static RiverUserResponseProto GetRootAsRiverUserResponseProto(ByteBuffer _bb, RiverUserResponseProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RiverUserResponseProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public UserResponseUnionWrapperBytesProto? Response { get { int o = __p.__offset(4); return o != 0 ? (UserResponseUnionWrapperBytesProto?)(new UserResponseUnionWrapperBytesProto()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public UserMessageUnionWrapperBytesProto? Messages(int j) { int o = __p.__offset(6); return o != 0 ? (UserMessageUnionWrapperBytesProto?)(new UserMessageUnionWrapperBytesProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MessagesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ConsoleLogBytesProto? ConsoleLog { get { int o = __p.__offset(8); return o != 0 ? (ConsoleLogBytesProto?)(new ConsoleLogBytesProto()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<RiverUserResponseProto> CreateRiverUserResponseProto(FlatBufferBuilder builder,
      Offset<UserResponseUnionWrapperBytesProto> responseOffset = default(Offset<UserResponseUnionWrapperBytesProto>),
      VectorOffset messagesOffset = default(VectorOffset),
      Offset<ConsoleLogBytesProto> console_logOffset = default(Offset<ConsoleLogBytesProto>)) {
    builder.StartTable(3);
    RiverUserResponseProto.AddConsoleLog(builder, console_logOffset);
    RiverUserResponseProto.AddMessages(builder, messagesOffset);
    RiverUserResponseProto.AddResponse(builder, responseOffset);
    return RiverUserResponseProto.EndRiverUserResponseProto(builder);
  }

  public static void StartRiverUserResponseProto(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddResponse(FlatBufferBuilder builder, Offset<UserResponseUnionWrapperBytesProto> responseOffset) { builder.AddOffset(0, responseOffset.Value, 0); }
  public static void AddMessages(FlatBufferBuilder builder, VectorOffset messagesOffset) { builder.AddOffset(1, messagesOffset.Value, 0); }
  public static VectorOffset CreateMessagesVector(FlatBufferBuilder builder, Offset<UserMessageUnionWrapperBytesProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMessagesVectorBlock(FlatBufferBuilder builder, Offset<UserMessageUnionWrapperBytesProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartMessagesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddConsoleLog(FlatBufferBuilder builder, Offset<ConsoleLogBytesProto> consoleLogOffset) { builder.AddOffset(2, consoleLogOffset.Value, 0); }
  public static Offset<RiverUserResponseProto> EndRiverUserResponseProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<RiverUserResponseProto>(o);
  }
};

