// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SaveDataRequestProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SaveDataRequestProto GetRootAsSaveDataRequestProto(ByteBuffer _bb) { return GetRootAsSaveDataRequestProto(_bb, new SaveDataRequestProto()); }
  public static SaveDataRequestProto GetRootAsSaveDataRequestProto(ByteBuffer _bb, SaveDataRequestProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SaveDataRequestProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public InboundDataDeltaProto? DataDeltas(int j) { int o = __p.__offset(4); return o != 0 ? (InboundDataDeltaProto?)(new InboundDataDeltaProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataDeltasLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SaveDataRequestProto> CreateSaveDataRequestProto(FlatBufferBuilder builder,
      VectorOffset data_deltasOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SaveDataRequestProto.AddDataDeltas(builder, data_deltasOffset);
    return SaveDataRequestProto.EndSaveDataRequestProto(builder);
  }

  public static void StartSaveDataRequestProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDataDeltas(FlatBufferBuilder builder, VectorOffset dataDeltasOffset) { builder.AddOffset(0, dataDeltasOffset.Value, 0); }
  public static VectorOffset CreateDataDeltasVector(FlatBufferBuilder builder, Offset<InboundDataDeltaProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataDeltasVectorBlock(FlatBufferBuilder builder, Offset<InboundDataDeltaProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDataDeltasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SaveDataRequestProto> EndSaveDataRequestProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // data_deltas
    return new Offset<SaveDataRequestProto>(o);
  }
};

