// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SaveDataResponseProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SaveDataResponseProto GetRootAsSaveDataResponseProto(ByteBuffer _bb) { return GetRootAsSaveDataResponseProto(_bb, new SaveDataResponseProto()); }
  public static SaveDataResponseProto GetRootAsSaveDataResponseProto(ByteBuffer _bb, SaveDataResponseProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SaveDataResponseProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public DataHandleProto? Handles(int j) { int o = __p.__offset(4); return o != 0 ? (DataHandleProto?)(new DataHandleProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int HandlesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SaveDataResponseProto> CreateSaveDataResponseProto(FlatBufferBuilder builder,
      VectorOffset handlesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SaveDataResponseProto.AddHandles(builder, handlesOffset);
    return SaveDataResponseProto.EndSaveDataResponseProto(builder);
  }

  public static void StartSaveDataResponseProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddHandles(FlatBufferBuilder builder, VectorOffset handlesOffset) { builder.AddOffset(0, handlesOffset.Value, 0); }
  public static VectorOffset CreateHandlesVector(FlatBufferBuilder builder, Offset<DataHandleProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateHandlesVectorBlock(FlatBufferBuilder builder, Offset<DataHandleProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartHandlesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SaveDataResponseProto> EndSaveDataResponseProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // handles
    return new Offset<SaveDataResponseProto>(o);
  }
};

