// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum SetupWorkerErrorUnionProto : byte
{
  NONE = 0,
  ErrorCodeResponseProto = 1,
  ExceptionResponseProto = 2,
};

