// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SetupWorkerResponseProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SetupWorkerResponseProto GetRootAsSetupWorkerResponseProto(ByteBuffer _bb) { return GetRootAsSetupWorkerResponseProto(_bb, new SetupWorkerResponseProto()); }
  public static SetupWorkerResponseProto GetRootAsSetupWorkerResponseProto(ByteBuffer _bb, SetupWorkerResponseProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetupWorkerResponseProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SetupWorkerErrorUnionProto ErrorType { get { int o = __p.__offset(4); return o != 0 ? (SetupWorkerErrorUnionProto)__p.bb.Get(o + __p.bb_pos) : SetupWorkerErrorUnionProto.NONE; } }
  public TTable? Error<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public ErrorCodeResponseProto ErrorAsErrorCodeResponseProto() { return Error<ErrorCodeResponseProto>().Value; }
  public ExceptionResponseProto ErrorAsExceptionResponseProto() { return Error<ExceptionResponseProto>().Value; }

  public static Offset<SetupWorkerResponseProto> CreateSetupWorkerResponseProto(FlatBufferBuilder builder,
      SetupWorkerErrorUnionProto error_type = SetupWorkerErrorUnionProto.NONE,
      int errorOffset = 0) {
    builder.StartTable(2);
    SetupWorkerResponseProto.AddError(builder, errorOffset);
    SetupWorkerResponseProto.AddErrorType(builder, error_type);
    return SetupWorkerResponseProto.EndSetupWorkerResponseProto(builder);
  }

  public static void StartSetupWorkerResponseProto(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddErrorType(FlatBufferBuilder builder, SetupWorkerErrorUnionProto errorType) { builder.AddByte(0, (byte)errorType, 0); }
  public static void AddError(FlatBufferBuilder builder, int errorOffset) { builder.AddOffset(1, errorOffset, 0); }
  public static Offset<SetupWorkerResponseProto> EndSetupWorkerResponseProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SetupWorkerResponseProto>(o);
  }
};

