// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SubscribeMessageResponseProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SubscribeMessageResponseProto GetRootAsSubscribeMessageResponseProto(ByteBuffer _bb) { return GetRootAsSubscribeMessageResponseProto(_bb, new SubscribeMessageResponseProto()); }
  public static SubscribeMessageResponseProto GetRootAsSubscribeMessageResponseProto(ByteBuffer _bb, SubscribeMessageResponseProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SubscribeMessageResponseProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSubscribeMessageResponseProto(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<SubscribeMessageResponseProto> EndSubscribeMessageResponseProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SubscribeMessageResponseProto>(o);
  }
};

