// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct SubscribeDataUpdatesRequestProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static SubscribeDataUpdatesRequestProto GetRootAsSubscribeDataUpdatesRequestProto(ByteBuffer _bb) { return GetRootAsSubscribeDataUpdatesRequestProto(_bb, new SubscribeDataUpdatesRequestProto()); }
  public static SubscribeDataUpdatesRequestProto GetRootAsSubscribeDataUpdatesRequestProto(ByteBuffer _bb, SubscribeDataUpdatesRequestProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SubscribeDataUpdatesRequestProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public DataReferenceValueProto? References(int j) { int o = __p.__offset(4); return o != 0 ? (DataReferenceValueProto?)(new DataReferenceValueProto()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ReferencesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SubscribeDataUpdatesRequestProto> CreateSubscribeDataUpdatesRequestProto(FlatBufferBuilder builder,
      VectorOffset referencesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SubscribeDataUpdatesRequestProto.AddReferences(builder, referencesOffset);
    return SubscribeDataUpdatesRequestProto.EndSubscribeDataUpdatesRequestProto(builder);
  }

  public static void StartSubscribeDataUpdatesRequestProto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddReferences(FlatBufferBuilder builder, VectorOffset referencesOffset) { builder.AddOffset(0, referencesOffset.Value, 0); }
  public static VectorOffset CreateReferencesVector(FlatBufferBuilder builder, Offset<DataReferenceValueProto>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateReferencesVectorBlock(FlatBufferBuilder builder, Offset<DataReferenceValueProto>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartReferencesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SubscribeDataUpdatesRequestProto> EndSubscribeDataUpdatesRequestProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // references
    return new Offset<SubscribeDataUpdatesRequestProto>(o);
  }
};

