// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct UnsubscribeMessageRequestProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static UnsubscribeMessageRequestProto GetRootAsUnsubscribeMessageRequestProto(ByteBuffer _bb) { return GetRootAsUnsubscribeMessageRequestProto(_bb, new UnsubscribeMessageRequestProto()); }
  public static UnsubscribeMessageRequestProto GetRootAsUnsubscribeMessageRequestProto(ByteBuffer _bb, UnsubscribeMessageRequestProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UnsubscribeMessageRequestProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort ClassId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public WorkerReferenceUnionProto SourceType { get { int o = __p.__offset(6); return o != 0 ? (WorkerReferenceUnionProto)__p.bb.Get(o + __p.bb_pos) : WorkerReferenceUnionProto.NONE; } }
  public TTable? Source<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public DataReferenceValueProto SourceAsDataReferenceValueProto() { return Source<DataReferenceValueProto>().Value; }
  public ServiceReferenceValueProto SourceAsServiceReferenceValueProto() { return Source<ServiceReferenceValueProto>().Value; }

  public static Offset<UnsubscribeMessageRequestProto> CreateUnsubscribeMessageRequestProto(FlatBufferBuilder builder,
      ushort class_id = 0,
      WorkerReferenceUnionProto source_type = WorkerReferenceUnionProto.NONE,
      int sourceOffset = 0) {
    builder.StartTable(3);
    UnsubscribeMessageRequestProto.AddSource(builder, sourceOffset);
    UnsubscribeMessageRequestProto.AddClassId(builder, class_id);
    UnsubscribeMessageRequestProto.AddSourceType(builder, source_type);
    return UnsubscribeMessageRequestProto.EndUnsubscribeMessageRequestProto(builder);
  }

  public static void StartUnsubscribeMessageRequestProto(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddClassId(FlatBufferBuilder builder, ushort classId) { builder.AddUshort(0, classId, 0); }
  public static void AddSourceType(FlatBufferBuilder builder, WorkerReferenceUnionProto sourceType) { builder.AddByte(1, (byte)sourceType, 0); }
  public static void AddSource(FlatBufferBuilder builder, int sourceOffset) { builder.AddOffset(2, sourceOffset, 0); }
  public static Offset<UnsubscribeMessageRequestProto> EndUnsubscribeMessageRequestProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 8);  // source
    return new Offset<UnsubscribeMessageRequestProto>(o);
  }
};

