// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct UserResponseUnionWrapperProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static UserResponseUnionWrapperProto GetRootAsUserResponseUnionWrapperProto(ByteBuffer _bb) { return GetRootAsUserResponseUnionWrapperProto(_bb, new UserResponseUnionWrapperProto()); }
  public static UserResponseUnionWrapperProto GetRootAsUserResponseUnionWrapperProto(ByteBuffer _bb, UserResponseUnionWrapperProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UserResponseUnionWrapperProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public UserResponseUnionProto ValueType { get { int o = __p.__offset(4); return o != 0 ? (UserResponseUnionProto)__p.bb.Get(o + __p.bb_pos) : UserResponseUnionProto.NONE; } }
  public TTable? Value<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public ErrorCodeResponseProto ValueAsErrorCodeResponseProto() { return Value<ErrorCodeResponseProto>().Value; }
  public ExceptionResponseProto ValueAsExceptionResponseProto() { return Value<ExceptionResponseProto>().Value; }
  public CallServiceMethodResponseProto ValueAsCallServiceMethodResponseProto() { return Value<CallServiceMethodResponseProto>().Value; }
  public GetDataResponseProto ValueAsGetDataResponseProto() { return Value<GetDataResponseProto>().Value; }
  public SaveDataResponseProto ValueAsSaveDataResponseProto() { return Value<SaveDataResponseProto>().Value; }
  public SubscribeMessageResponseProto ValueAsSubscribeMessageResponseProto() { return Value<SubscribeMessageResponseProto>().Value; }
  public UnsubscribeMessageResponseProto ValueAsUnsubscribeMessageResponseProto() { return Value<UnsubscribeMessageResponseProto>().Value; }
  public SubscribeDataUpdatesResponseProto ValueAsSubscribeDataUpdatesResponseProto() { return Value<SubscribeDataUpdatesResponseProto>().Value; }
  public UnsubscribeDataUpdatesResponseProto ValueAsUnsubscribeDataUpdatesResponseProto() { return Value<UnsubscribeDataUpdatesResponseProto>().Value; }

  public static Offset<UserResponseUnionWrapperProto> CreateUserResponseUnionWrapperProto(FlatBufferBuilder builder,
      UserResponseUnionProto value_type = UserResponseUnionProto.NONE,
      int valueOffset = 0) {
    builder.StartTable(2);
    UserResponseUnionWrapperProto.AddValue(builder, valueOffset);
    UserResponseUnionWrapperProto.AddValueType(builder, value_type);
    return UserResponseUnionWrapperProto.EndUserResponseUnionWrapperProto(builder);
  }

  public static void StartUserResponseUnionWrapperProto(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddValueType(FlatBufferBuilder builder, UserResponseUnionProto valueType) { builder.AddByte(0, (byte)valueType, 0); }
  public static void AddValue(FlatBufferBuilder builder, int valueOffset) { builder.AddOffset(1, valueOffset, 0); }
  public static Offset<UserResponseUnionWrapperProto> EndUserResponseUnionWrapperProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UserResponseUnionWrapperProto>(o);
  }
};

