// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum UserRequestUnionProto : byte
{
  NONE = 0,
  CallServiceMethodRequestProto = 1,
  GetDataRequestProto = 2,
  SaveDataRequestProto = 3,
  SubscribeMessageRequestProto = 4,
  UnsubscribeMessageRequestProto = 5,
  SubscribeDataUpdatesRequestProto = 6,
  UnsubscribeDataUpdatesRequestProto = 7,
};

