// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum UserMessageUnionProto : byte
{
  NONE = 0,
  DataUpdateMessageProto = 1,
  MessageMessageProto = 2,
};

