// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ValueProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static ValueProto GetRootAsValueProto(ByteBuffer _bb) { return GetRootAsValueProto(_bb, new ValueProto()); }
  public static ValueProto GetRootAsValueProto(ByteBuffer _bb, ValueProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ValueProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ValueUnionProto ValueType { get { int o = __p.__offset(4); return o != 0 ? (ValueUnionProto)__p.bb.Get(o + __p.bb_pos) : ValueUnionProto.NONE; } }
  public TTable? Value<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public UndefinedValueProto ValueAsUndefinedValueProto() { return Value<UndefinedValueProto>().Value; }
  public NullValueProto ValueAsNullValueProto() { return Value<NullValueProto>().Value; }
  public BooleanValueProto ValueAsBooleanValueProto() { return Value<BooleanValueProto>().Value; }
  public StringValueProto ValueAsStringValueProto() { return Value<StringValueProto>().Value; }
  public NumberValueProto ValueAsNumberValueProto() { return Value<NumberValueProto>().Value; }
  public ObjectValueProto ValueAsObjectValueProto() { return Value<ObjectValueProto>().Value; }
  public ArrayValueProto ValueAsArrayValueProto() { return Value<ArrayValueProto>().Value; }
  public DataReferenceValueProto ValueAsDataReferenceValueProto() { return Value<DataReferenceValueProto>().Value; }
  public ServiceReferenceValueProto ValueAsServiceReferenceValueProto() { return Value<ServiceReferenceValueProto>().Value; }
  public MapValueProto ValueAsMapValueProto() { return Value<MapValueProto>().Value; }
  public SetValueProto ValueAsSetValueProto() { return Value<SetValueProto>().Value; }
  public DateValueProto ValueAsDateValueProto() { return Value<DateValueProto>().Value; }

  public static Offset<ValueProto> CreateValueProto(FlatBufferBuilder builder,
      ValueUnionProto value_type = ValueUnionProto.NONE,
      int valueOffset = 0) {
    builder.StartTable(2);
    ValueProto.AddValue(builder, valueOffset);
    ValueProto.AddValueType(builder, value_type);
    return ValueProto.EndValueProto(builder);
  }

  public static void StartValueProto(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddValueType(FlatBufferBuilder builder, ValueUnionProto valueType) { builder.AddByte(0, (byte)valueType, 0); }
  public static void AddValue(FlatBufferBuilder builder, int valueOffset) { builder.AddOffset(1, valueOffset, 0); }
  public static Offset<ValueProto> EndValueProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ValueProto>(o);
  }
};

