// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum WorkerReferenceUnionProto : byte
{
  NONE = 0,
  DataReferenceValueProto = 1,
  ServiceReferenceValueProto = 2,
};

