// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct WorkerProcessEndpointProto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static WorkerProcessEndpointProto GetRootAsWorkerProcessEndpointProto(ByteBuffer _bb) { return GetRootAsWorkerProcessEndpointProto(_bb, new WorkerProcessEndpointProto()); }
  public static WorkerProcessEndpointProto GetRootAsWorkerProcessEndpointProto(ByteBuffer _bb, WorkerProcessEndpointProto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WorkerProcessEndpointProto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort SetupWorkerPort { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort DeleteWorkerPort { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort UserPort { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<WorkerProcessEndpointProto> CreateWorkerProcessEndpointProto(FlatBufferBuilder builder,
      ushort setup_worker_port = 0,
      ushort delete_worker_port = 0,
      ushort user_port = 0) {
    builder.StartTable(3);
    WorkerProcessEndpointProto.AddUserPort(builder, user_port);
    WorkerProcessEndpointProto.AddDeleteWorkerPort(builder, delete_worker_port);
    WorkerProcessEndpointProto.AddSetupWorkerPort(builder, setup_worker_port);
    return WorkerProcessEndpointProto.EndWorkerProcessEndpointProto(builder);
  }

  public static void StartWorkerProcessEndpointProto(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddSetupWorkerPort(FlatBufferBuilder builder, ushort setupWorkerPort) { builder.AddUshort(0, setupWorkerPort, 0); }
  public static void AddDeleteWorkerPort(FlatBufferBuilder builder, ushort deleteWorkerPort) { builder.AddUshort(1, deleteWorkerPort, 0); }
  public static void AddUserPort(FlatBufferBuilder builder, ushort userPort) { builder.AddUshort(2, userPort, 0); }
  public static Offset<WorkerProcessEndpointProto> EndWorkerProcessEndpointProto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WorkerProcessEndpointProto>(o);
  }
};

