//
// Originally written by Scott R. Jones.
// Copyright (c) 2021 Warpdrive Technologies, Inc. All rights reserved.
//

#pragma once
#define _ESTATE_STRINGIFY(x) #x
#define ESTATE_STRINGIFY(x) _ESTATE_STRINGIFY(x)

//NOTE: This must match what's defined in Jayne/Services/Impl/JavaScriptParserServiceImpl.cs
#define ESTATE_INTERNAL(x) __internal_estate_##x
#define ESTATE_INTERNAL_STR(x) ESTATE_STRINGIFY(ESTATE_INTERNAL(x))
#define ESTATE_SYSTEM_OBJECT_NAME "system"
#define ESTATE_KERNEL_MODULE_NAME "worker-runtime"
#define ESTATE_KERNEL_INTERNAL_MODULE_NAME "worker-runtime-internal"
#define ESTATE_CREATE_UUID_FUNCTION createUuid
#define ESTATE_CREATE_UUID_FUNCTION_STR ESTATE_STRINGIFY(ESTATE_CREATE_UUID_FUNCTION)
#define ESTATE_GET_SERVICE_FUNCTION getService
#define ESTATE_GET_SERVICE_FUNCTION_STR ESTATE_STRINGIFY(ESTATE_GET_SERVICE_FUNCTION)
#define ESTATE_REVERT_FUNCTION revert
#define ESTATE_REVERT_FUNCTION_STR ESTATE_STRINGIFY(ESTATE_REVERT_FUNCTION)
#define ESTATE_GET_DATA_FUNCTION getData
#define ESTATE_GET_DATA_FUNCTION_STR ESTATE_STRINGIFY(ESTATE_GET_DATA_FUNCTION)
#define ESTATE_DELETE_FUNCTION delete_
#define ESTATE_DELETE_FUNCTION_STR "delete"
#define ESTATE_SAVE_DATA_GRAPHS_FUNCTION saveDataGraphs
#define ESTATE_SAVE_DATA_GRAPHS_FUNCTION_STR ESTATE_STRINGIFY(ESTATE_SAVE_DATA_GRAPHS_FUNCTION)
#define ESTATE_SAVE_DATA_FUNCTION saveData
#define ESTATE_SAVE_DATA_FUNCTION_STR ESTATE_STRINGIFY(ESTATE_SAVE_DATA_FUNCTION)
#define ESTATE_SEND_MESSAGE_FUNCTION sendMessage
#define ESTATE_SEND_MESSAGE_FUNCTION_STR ESTATE_STRINGIFY(ESTATE_SEND_MESSAGE_FUNCTION)
#define ESTATE_CONSOLE_OBJECT_NAME "console"
#define ESTATE_EVAL_FUNCTION_NAME "eval"
#define ESTATE_CONSOLE_LOG_FUNCTION log
#define ESTATE_CONSOLE_LOG_FUNCTION_STR ESTATE_STRINGIFY(ESTATE_CONSOLE_LOG_FUNCTION)
#define ESTATE_CONSOLE_ERROR_FUNCTION error
#define ESTATE_CONSOLE_ERROR_FUNCTION_STR ESTATE_STRINGIFY(ESTATE_CONSOLE_ERROR_FUNCTION)
#define ESTATE_NEW_MESSAGE_CTOR Message
#define ESTATE_NEW_SERVICE_CTOR Service
#define ESTATE_NEW_DATA_CTOR Data
#define ESTATE_NEW_MESSAGE_CTOR_STR ESTATE_STRINGIFY(ESTATE_NEW_MESSAGE_CTOR)
#define ESTATE_NEW_SERVICE_CTOR_STR ESTATE_STRINGIFY(ESTATE_NEW_SERVICE_CTOR)
#define ESTATE_NEW_DATA_CTOR_STR ESTATE_STRINGIFY(ESTATE_NEW_DATA_CTOR)
#define ESTATE_EXISTING_SERVICE_CTOR ESTATE_INTERNAL(Service)
#define ESTATE_EXISTING_DATA_CTOR ESTATE_INTERNAL(Data)
#define ESTATE_EXISTING_SERVICE_CTOR_STR ESTATE_STRINGIFY(ESTATE_EXISTING_SERVICE_CTOR)
#define ESTATE_EXISTING_DATA_CTOR_STR ESTATE_STRINGIFY(ESTATE_EXISTING_DATA_CTOR)
#define ESTATE_GRAFT_FUNC_PREFIX ESTATE_INTERNAL_STR(graft_)
#define ESTATE_GRAFT_FUNC_FORMAT (ESTATE_GRAFT_FUNC_PREFIX "{0}")
#define ESTATE_NEW_FUNC_PREFIX ESTATE_INTERNAL_STR(new_)
#define ESTATE_NEW_FUNC_FORMAT (ESTATE_NEW_FUNC_PREFIX "{0}")
#define ESTATE_PASSTHROUGH_CLASS_NAME_PREFIX ESTATE_INTERNAL_STR(passthrough_)
#define ESTATE_PASSTHROUGH_CLASS_NAME_FORMAT (ESTATE_PASSTHROUGH_CLASS_NAME_PREFIX "{0}")
#define ESTATE_OBJECT_PROPERTIES_INDEX_INITIAL_BUFFER_SIZE (1024)
#define ESTATE_OBJECT_INSTANCE_INITIAL_BUFFER_SIZE (100)
#define ESTATE_MODULE_SOURCE_FILE_NAME_FORMAT "worker://{0}/{1}"
